#!/usr/bin/env bash
# A simple script that updates the licences and README files across the workspace.
# The README file is taken from the kaitai subdirectory as it is generated by cargo-readme.
# The licences are taken from the root directory.

# Licences
cp LICENSE-MIT kaitai/
cp LICENSE-APACHE kaitai/

cp LICENSE-MIT kaitai-macros/
cp LICENSE-APACHE kaitai-macros/

# README
cp kaitai/README.md .